version: '3.8'

services:
  redis:
    container_name: redis-cache
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis:
